### PR TITLE
Shrunk Canvas Size

### PR DESCRIPTION
**Pull request by JohnnyUrosevic**
Made it fit on screen so that there is no scrollbars on desktop and you can see the whole board without it being cut off

### CODE REVIEW

**Comment by Kimeiga** [comment]
LOVE YA JOHNNY

**Comment by Kimeiga** [comment]
although i don't think there were any scrollbars on desktop. I tried it with aero 14 chromium and macbook pro 2016 chromium

**Comment by Kimeiga** [comment]
the real problem is that it's difficult to play on mobile. I should really just add a button that appears when it detects that the user is on a phone that says "fullscreen", and use the p5js solutions for fullscreen then.

**Comment by JohnnyUrosevic** [comment]
Yeah I was getting scrollbars on my pc monitor, maybe I'll look into detecting mobile and adjusting accordingly?

**Comment by Kimeiga** [comment]
sure mate! It was like extremely hard because each mobile browser has different safe areas but I'm also not that good at this

**Pull request merged**
